### ISSUE TITLE
errors after initial run after install => ida 6.95.160808

### ISSUE THREAD

**Issue by vyrus001** [rr-/ida-images#6]
```
IDAPython: Error while calling Python callback <OnCreate>:
Traceback (most recent call last):
  File "C:/Program Files (x86)/IDA 6.95/plugins/rgb-ida.py", line 33, in OnCreate
    self.parent = self.FormToPySideWidget(form)
  File "C:\Program Files (x86)\IDA 6.95\python\ida_kernwin.py", line 5673, in FormToPySideWidget
    return ctx.QtGui.QWidget.FromCObject(form)
AttributeError: type object 'PySide.QtGui.QWidget' has no attribute 'FromCObject'
```

**Comment by rr-** [comment]
This is weird, it's like IDA has problem with itself internally

**Comment by rr-** [comment]
I believe this is a problem within IDAPython:

https://github.com/idapython/src/blob/master/pywraps/py_kernwin_plgform.py#L84

**Comment by rr-** [comment]
I don't think I'm able to debug it, since the trial version of 6.95 doesn't seem to ship with up-to-date IDAPython, and using the available binaries from GitHub has problems with importing `PyQt5` that we're supposed to use from 6.9+.

**Comment by ThoBre** [comment]
Try to add this at the beginning of rgb-ida.py:

from PySide import QtCore, QtGui

**Comment by rr-** [comment]
Should be better
