### ISSUE TITLE
Doesn't work in IDA 6.8?

### ISSUE THREAD

**Issue by danilaml** [rr-/ida-images#7]
![image](https://user-images.githubusercontent.com/2046350/32123413-bc685d62-bb6c-11e7-886a-8fabe9215d78.png)

Tried with idapython 1.7.0 and 1.7.2

**Comment by rr-** [comment]
Should be better

**Comment by danilaml** [comment]
@rr- thanks. The error doesn't show up now. Though it doesn't do what I hoped it'd do (show mbp image embedded in the binary), but good enough! 👍
