### ISSUE TITLE
How hard is to add 1 bit color depth support? (Black/White)

### ISSUE THREAD

**Issue by ValkA** [rr-/ida-images#8]
specifically this one :)
https://godoc.org/periph.io/x/periph/devices/ssd1306/image1bit

I'll try to add it to your code if its not too complicated :)

**Comment by rr-** [comment]
All supported formats are mapped to Qt pixel formats [here](https://github.com/rr-/ida-images/blob/master/librgb/renderer.py#L20).
Qt supports 1 bit pixel format: [QImage::Format_Mono](http://doc.qt.io/qt-5/qimage.html)

So the only thing you'd need to take care of (besides adding a new mapping) would be to add support for 1-bit values in image stride [here](https://github.com/rr-/ida-images/blob/master/librgb/renderer.py#L48-L103).

**Comment by ValkA** [comment]
Cool, I've figured that out right now :) you'll get a PR soon

**Comment by rr-** [comment]
Merged in #9
